# Generated by Django 3.2.6 on 2022-03-24 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
