# Generated by Django 4.0.2 on 2022-04-07 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_id', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(default='None', max_length=30)),
                ('status', models.CharField(max_length=30, null=True)),
                ('total_payment', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
