# Generated by Django 4.0.2 on 2022-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
