# Generated by Django 4.0.2 on 2022-04-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_price'),
        ('payment', '0003_shoppingcart_rename_total_payment_order_total_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCartItems',
            new_name='ShoppingCartItem',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_price',
        ),
    ]
