# Generated by Django 4.0.2 on 2022-05-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_shoppingcartitems_shoppingcartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='order',
        ),
    ]
