# Generated by Django 4.0.2 on 2022-05-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_order_address_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
