# Generated by Django 4.0.2 on 2022-05-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_shoppingcartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='status',
        ),
    ]
