# Generated by Django 4.0.2 on 2022-05-17 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_price'),
        ('payment', '0005_alter_shoppingcartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
