# Generated by Django 4.0.2 on 2022-05-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
