# Generated by Django 4.0.2 on 2022-05-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_shoppingcartitem_product'),
        ('payment', '0008_shoppingcartitem_status'),
    ]

    operations = [
    ]
