# Generated by Django 4.0.2 on 2022-05-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_price'),
        ('payment', '0009_merge_20220517_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobileNumber',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
