# Generated by Django 4.0.2 on 2022-05-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_order_mobilenumber_order_payment_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
            preserve_default=False,
        ),
    ]
