# Generated by Django 4.0.2 on 2022-05-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_shoppingcartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mobileNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
    ]
