# Generated by Django 3.2.6 on 2022-03-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='customer', max_length=60),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='contact_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
