# Generated by Django 3.2.6 on 2022-04-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_address_alter_account_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['email']},
        ),
    ]
